### ISSUE TITLE
Add debugger screenshots

### ISSUE THREAD

**Issue by drewnoakes** [Fody/Visualize#10]
This looks convenient, mostly to stop having to expand the 'results view' in the debugger all the time.

You should definitely show a before/after screenshot of the debug inspector on the README so that folks can grok what this addin offers them.

**Comment by distantcam** [comment]
Oooh that's a really good idea! Did you want to submit a PR?

**Comment by drewnoakes** [comment]
At this stage I'm just window shopping :)

If I do try Fody out, and Visualize, I'll make a PR. Right now I don't have
a suitable project.

**Comment by SimonCropp** [comment]
Looking forward to that pr ;)

**Comment by drewnoakes** [comment]
Unfortunately I never did find a compelling use case for any of the Fody tools.

**Comment by SimonCropp** [comment]
Reasonable conclusion. Don't add tooling if the value is not justified
