### ISSUE TITLE
Not working on Web API Framework project

### ISSUE THREAD

**Issue by asherber** [Fody/Visualize#15]
I installed the latest package from NuGet in a Web API framework project, but when I build, I get:
```
2>    Fody: Fody (version 1.29.2.0) Executing
2>      Fody/Visualize:   	No reference to 'Visualize.dll' found. References not modified.
2>    Fody:   Finished Fody 539ms.
2>  Email.Api -> P:\Foo.Api\bin\Foo.Api.dll
2>    Fody:   Skipped Verifying assembly since it is disabled in configuration
2>    Fody:   Finished verification in 3ms.
```
The `Foo.Api` project does have a reference to `Visualize.dll`, but I notice that it's pointing to the version in the `dotnet` directory. I tried changing this reference in the project file to the `portable...` directory, but that didn't help.

**Comment by SimonCropp** [comment]
can u upload a repro for this issue

**Comment by asherber** [comment]
Seems to be working now, with the latest versions of things. Closing.
