### ISSUE TITLE
Can this be restricted to Debug builds only?

### ISSUE THREAD

**Issue by drewnoakes** [Fody/Visualize#9]
Is it straightforward to ensure this only applies to Debug builds? Would this be controlled by this addin, or beforehand by configuring Fody?

**Comment by distantcam** [comment]
It's easy enough to modify the weaver to allow this, and set it up in the config.

What's the reason for not including the attributes in release builds?

**Comment by drewnoakes** [comment]
The visualiser classes and to a lesser extent attributes increase the size of the DLL. There are cases where optimising for size is important. Code that has many classes is particularly prone to bloat. Though I fully admit I haven't tested this yet.

**Comment by distantcam** [comment]
> There are cases where optimising for size is important.

Still using tape drives?

**Comment by SimonCropp** [comment]
yeah for any real world app this project adds a trivial amount of size to your assembly.

**Comment by drewnoakes** [comment]
It's true that disk storage space is rarely a concern these days. However reducing the amount of IL consequently reduces load and verification times, and reduces the size of runtime type information data structures, allowing them to fit more efficiently in memory and with better cache locality. For certain classes of application, these things matter. However all of this is conjecture without actual data on how much overhead the generated IL introduces on real world code bases. Such data could make a nice addition to the project's description.

Regardless of the above, I'd still want to be able to turn this off for release builds before using it on any serious project.

**Comment by distantcam** [comment]
It sounds like you don't trust the code that this project injects. That's fine. But I'm not going to put in the enormous amount of effort to collect data on load times of assemblies that do and don't use visualize.

To turn off visualize in your project simply uninstall it.
